modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aurilisdev/Nuclear-Science" #optional
[[mods]] #mandatory
modId="nuclearscience" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Nuclear Science" #mandatory
displayURL="https://github.com/aurilisdev/Nuclear-Science" #optional
logoFile="nuclearscience.png" #optional
credits="Thanks to all contributors" #optional
authors="aurilisdev" #optional
description='''
'''
[[dependencies.nuclearscience]]
    modId="electrodynamics"
    mandatory=true
    versionRange="[1.20.1-0.9,)"
    ordering="NONE"
    side="BOTH"